### ISSUE TITLE
Update missing MetaCyc2GO mappings for SGD YeastPathways

### ISSUE THREAD

**Issue by dustine32** [geneontology/yeast-pathways-go-cams#7]
@balhoff @cmungall We now have the complete set of Metacyc2GO BP mappings for all YeastPathways models thanks to @suzialeksander @srengel. [yeast_pathway_id_labels_gos_gps121322.xlsx](https://github.com/geneontology/go-ontology/files/10250018/yeast_pathway_id_labels_gos_gps121322.xlsx)

How can we get these updated in the GO ontology? Is it as simple as reformatting them into this [metacyc2go](https://github.com/geneontology/go-ontology/blob/master/src/ontology/external2go/metacyc2go) GH file?

Once they're in the ontology they will be added to models on the next YeastPathways GO-CAM regen as described in https://github.com/geneontology/pathways2GO/issues/159#issuecomment-1343184595.

**Comment by pgaudet** [comment]
this is not the current issue anymore. Manual mapping were done by Suzi and Stacia
